
name: Building release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile_ImageClassificatorCLI:
    name: Compile ImageClassificatorCLI into executable file
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r ImageClassificatorCLI/requirements.txt
      - name: Determine version
        run: echo "::set-output name=version::$(python ./ImageClassificatorCLI/ImageClassificatorCLI.py --version)"
        id: version
      - name: Create executable
        run: pyinstaller ./ImageClassificatorCLI/ImageClassificatorCLI.py
      - name: Copy content
        run: Copy-Item ./ImageClassificatorCLI/mobilenet -Destination ./dist/ImageClassificatorCLI -Recurse
      - name: Zip Folder
        run: Compress-Archive -Path ./dist/ImageClassificatorCLI/* -DestinationPath ./ImageClassificatorCLI.zip
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ImageClassificatorCLI.zip
          asset_name: ImageClassificatorCLI.zip
          asset_content_type: application/zip
